CREATE TABLE User (
	id INT generated by default as identity (start with 10),
	name VARCHAR(255) NULL,	
	age INT NOT NULL,
	PRIMARY KEY (id)
);

INSERT INTO User (id, name, age) VALUES (0, 'First user', 33);