CREATE TABLE User (
	id INT generated by default as identity (start with 10),
	name VARCHAR(255) NULL,	
	age INT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE Anchor (
	id INT generated by default as identity (start with 10),
	name VARCHAR(255) NOT NULL,	
	relativePosition VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE Bone (
	id INT generated by default as identity (start with 10),
	PRIMARY KEY (id),
	FOREIGN KEY (id) REFERENCES Anchor(id)
);

CREATE TABLE Fascia (
	id INT generated by default as identity (start with 10),
	PRIMARY KEY (id),
	FOREIGN KEY (id) REFERENCES Anchor(id)
);

CREATE TABLE Joint (
	id INT generated by default as identity (start with 10),
	name VARCHAR(255) NOT NULL,	
	relativePosition VARCHAR(255) NOT NULL,
	bone1Id INT NOT NULL,
	bone2Id INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (bone1Id) REFERENCES Bone(id),
	FOREIGN KEY (bone2Id) REFERENCES Bone(id)
);

CREATE TABLE Muscle (
	id INT generated by default as identity (start with 10),
	name VARCHAR(255) NOT NULL,	
	relativePosition VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE MuscleAnchor (
	muscleId INT NOT NULL,
	anchorId INT NOT NULL,
	PRIMARY KEY (muscleId, anchorId),
	FOREIGN KEY (muscleId) REFERENCES Muscle(id),
	FOREIGN KEY (anchorId) REFERENCES Anchor(id)
);
